### PR TITLE
(#11) Fix return value for apt_update

### LINKED ISSUE #11: `mco package apt_update` is broken
Running `mco package apt_update` on Debian GNU/Linux systems fails with:

```sh-session
% mco package apt_update      
Do you really want to operate on packages unfiltered? (y/n): y

 * [ ============================================================> ] 21 / 21


The package application failed to run, use -v for full error backtrace details: undefined method `map' for nil:NilClass

% mco package apt_update -I /vps/ -v    
Discovering hosts using the mc method for 2 second(s) .... 8

 * [ ============================================================> ] 8 / 8


The package application failed to run: undefined method `map' for nil:NilClass

undefined method `map' for nil:NilClass (NoMethodError)
	from /usr/local/share/mcollective/application/package.rb:97:in `block in main'  <----
	from /usr/local/share/mcollective/application/package.rb:91:in `each'
	from /usr/local/share/mcollective/application/package.rb:91:in `main'
	from /usr/local/lib/ruby/site_ruby/2.4/mcollective/application.rb:293:in `run'
	from /usr/local/lib/ruby/site_ruby/2.4/mcollective/applications.rb:23:in `run'
	from /usr/local/bin/mco:33:in `<main>'
```

### PR DESCRIPTION
**Pull request by smortex**
On the agent side apt_update, update the packages information and
returns the status of this operation (success and failure), while the
application side expect a list of outdated packages to be provided.

This list of outdated packages is available using the apt_checkupdates
action of the agent.

Fix this issue by calling the apt_checkupdates method and return it's
value if the update succeeds.

Fixes #11

### CODE REVIEW

File: agent/package.rb [hunk 1]
```diff
@@ -45,6 +45,7 @@ class Package<RPC::Agent
         result = package_helper.apt_update
         reply[:exitcode] = result[:exitcode]
         reply[:output] = result[:output]
+        reply[:outdated_packages] = result[:outdated_packages]
```
Comment (ripienaar) [inline agent/package.rb]: we will need to add `:outdated_packages` to the DDL as well - will work without but it helps a lot to have it.

Comment (smortex) [reply agent/package.rb]: Good catch!  I amended the commit accordingly.

**Comment by smortex** [comment]
Hello!  I am checking old issues, and I feel like this one is ready to merge if it's okay for you.  Do you have remaining concerns regarding this PR or has it just been forgotten and is mergeable?  Thanks!
